import {
  RABBITMQ_EXCHANGES,
  RABBITMQ_QUEUES,
  RABBITMQ_ROUTING_KEYS,
} from '../../core/rabbitmq/rabbitmq.constants';

export const WORKFLOW_AGENT_EXCHANGE = RABBITMQ_EXCHANGES.AGENT;

export const FINANCE_KNOWLEDGE_SYNC_QUEUE =
  RABBITMQ_QUEUES.FINANCE_KNOWLEDGE_SYNC;

export const FINANCE_KNOWLEDGE_SYNC_ROUTING_KEY =
  RABBITMQ_ROUTING_KEYS.FINANCE_KNOWLEDGE_SYNC;
