export enum WorkflowName {
  FINANCE_KNOWLEDGE_SYNC = 'FINANCE_KNOWLEDGE_SYNC',
  FINANCE_QUERY_ANSWERING = 'FINANCE_QUERY_ANSWERING',
}

export enum WorkflowVersion {
  V1 = 'v1',
}

export enum WorkflowScopeType {
  WORKSPACE = 'WORKSPACE',
  ORG = 'ORG',
  USER = 'USER',
}

export enum WorkflowTriggerSource {
  API = 'API',
  SCHEDULE = 'SCHEDULE',
  SYSTEM = 'SYSTEM',
  WEBHOOK = 'WEBHOOK',
}

export enum WorkflowRunStatus {
  PENDING = 'PENDING',
  PLANNING = 'PLANNING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum WorkflowTaskType {
  FINANCE_KNOWLEDGE_SYNC = 'FINANCE_KNOWLEDGE_SYNC',
  EVIDENCE_RETRIEVAL = 'EVIDENCE_RETRIEVAL',
  RESPONSE_AGGREGATION = 'RESPONSE_AGGREGATION',
}

export enum WorkflowTaskStatus {
  PENDING = 'PENDING',
  QUEUED = 'QUEUED',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
  CANCELLED = 'CANCELLED',
}

export enum AgentName {
  FINANCE_KNOWLEDGE_SYNC_AGENT = 'FINANCE_KNOWLEDGE_SYNC_AGENT',
  EVIDENCE_RETRIEVAL_AGENT = 'EVIDENCE_RETRIEVAL_AGENT',
  RESPONSE_AGGREGATION_AGENT = 'RESPONSE_AGGREGATION_AGENT',
}

export enum AgentRunStatus {
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
